### ISSUE TITLE
Error in step 1

### ISSUE THREAD

**Issue by Dimple-sethi** [beom-kwon/bmi-classification#1]
Hi 
I am working in the gait analysis domain. I was exploring your code and faced some issues. In the very first step, I am facing an error. Help me resolve that.
Index exceeds the number of array elements (1).

Error in step1_data_transformation_from_txt_to_csv
(line 40)
            val2 = str2double(A{2}); % x-coordinate

**Comment by beom-kwon** [comment]
Hi, thank you for your interest in my source code.
Please set a breakpoint at line 39 of 'step1_data_transformation_from_txt_to_csv.' 
After executing the source code, in the work pace, you will find a variables 'A' which is a 1x4 cell.
The variables 'A' contains the following data: 'Head' '-0.02845094' '0.7953885' '2.586351.'
This data is the same as the first line of 1.txt for Person001.
Please let me know if you obtain the same result.

val1 = A{1};   % 'Head'
val2 = A{2};   % -0.02845094
val3 = A{3};   % 0.7953885
val4 = A{4};   % 2.586351
